### PR TITLE
Created Button component

### PR DESCRIPTION
**Pull request by anushasunil**
https://user-images.githubusercontent.com/90134948/151864892-37458a49-5cd8-4013-8f4c-1ac0cda9f61e.mp4

### CODE REVIEW

**Review by tushartiwari7 — APPROVED** [review]
You included a lot of variations of buttons. That's good work. 👍

**Comment by nishasen** [comment]
The button variations looks good and you have used variables in css that is making the code clean. Good work

**Review by horsemaker — APPROVED** [review]
looks good to go!

**Comment by aishwarya-bm** [comment]
Looks good to merge! Amazing work!

**Pull request merged**
